
apiVersion: apps/v1
kind: Deployment
metadata:
  name: MergeSense-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MergeSense-frontend
  template:
    metadata:
      labels:
        app: MergeSense-frontend
    spec:
      containers:
        - name: frontend
          image: yourrepo/MergeSense-frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: MergeSense-frontend
spec:
  selector:
    app: MergeSense-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
