
apiVersion: apps/v1
kind: Deployment
metadata:
  name: MergeSense-redis
spec:
  selector:
    matchLabels:
      app: MergeSense-redis
  template:
    metadata:
      labels:
        app: MergeSense-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: MergeSense-redis
spec:
  selector:
    app: MergeSense-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
